[tool.poetry]
name = "package-a"
version = "0.1.0"
description = ""
authors = ["lambdalisue <lambdalisue@hashnote.net>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"
